const Data = [
  {
    id: 1,
    category: "education",
    icon: "icon-graduation",
    year: "2015 - 2019",
    title: "Gymnasium",
    desc: "Degree",
  },
  {
    id: 2,
    category: "education",
    icon: "icon-graduation",
    year: "2021 - present",
    title: "Information technology in Belgrade",
    desc: "Studies",
  },
  {
    id: 3,
    category: "education",
    icon: "icon-graduation",
    year: "2021 - 2022",
    title: "ASP.Net Basics and Applications Certificate by Claster NIT",
    desc: "Finished",
  },
  {
    id: 3,
    category: "education",
    icon: "icon-graduation",
    year: "2021 - 2022",
    title: "C# programming Certificate by Claster NIT",
    desc: "Finished",
  },
  {
    id: 7,
    category: "experience",
    icon: "icon-briefcase",
    year: "2023 - present",
    title: "Full Stack Developer React/Go",
    desc: "ILM Education Center – Focused primarily on frontend development using React, building dynamic and responsive interfaces while designing intuitive user experiences. Integrated APIs and collaborated on application architecture, and in recent months began working with Golang to develop backend services, expanding my full-stack development skills. This experience strengthened my problem-solving abilities and provided hands-on insight into building efficient, scalable web applications.",
  },
  {
    id: 6,
    category: "experience",
    icon: "icon-briefcase",
    year: "Feb 2025 - Jun 2025",
    title: "Creative Designer & Video Editor ",
    desc: "Pester TV – Managed post-production workflow, led YouTube and social media content strategy, and redesigned broadcast visuals to enhance quality, efficiency, and audience engagement.",
  },
  {
    id: 4,
    category: "experience",
    icon: "icon-briefcase",
    year: "2021 - 2025",
    title: "Freelance",
    desc: "Developed and designed multiple freelance projects including the Ramazan Tracker Web App (React, Tailwind), Mufty Foundation Website (React, Figma), and several business landing pages and portfolio sites, combining modern frontend development with creative visual design and motion graphics for enhanced digital presence.Developed and designed multiple freelance projects including the Ramazan Tracker Web App (React, Tailwind), Mufty Foundation Website (React, Figma), and several business landing pages and portfolio sites, combining modern frontend development with creative visual design and motion graphics for enhanced digital presence.",
  },
  {
    id: 5,
    category: "experience",
    icon: "icon-briefcase",
    year: "2020 - 2021 ",
    title: "Back end developer .NET ",
    desc: "Klaster NIT Novi Pazar -  I collaborated with a talented team of developers, soaking in knowledge and honing my skills in the dynamic, collaborative environment, contributing to the seamless creation of solutions that navigate the digital world with ease. ",
  },
];

export default Data;
