const Data = [
  {
    id: 1,
    category: "education",
    icon: "icon-graduation",
    year: "2015 - 2019",
    title: "Degree",
    desc: "Gymnasium",
  },
  {
    id: 2,
    category: "education",
    icon: "icon-graduation",
    year: "2021 - present",
    title: "Bachelor's Degree",
    desc: "Information technology in Belgrade ",
  },
  {
    id: 3,
    category: "education",
    icon: "icon-graduation",
    year: "2021 - 2022",
    title: "Finished",
    desc: "ASP.Net Basics and Applications Certificate by Claster NIT",
  },
  {
    id: 3,
    category: "education",
    icon: "icon-graduation",
    year: "2021 - 2022",
    title: "Finished",
    desc: "C# programming Certificate by Claster NIT",
  },
  {
    id: 4,
    category: "experience",
    icon: "icon-briefcase",
    year: "2020 - 2023",
    title: "Graphic designer - video editor",
    desc: "Studio Hane Luxembourg",
  },
  {
    id: 5,
    category: "experience",
    icon: "icon-briefcase",
    year: "2019 - 2020 ",
    title: "Back end developer C#",
    desc: "Klaster NIT - Novi Pazar ",
  },
  {
    id: 6,
    category: "experience",
    icon: "icon-briefcase",
    year: "2023 - present",
    title: "Full Stack Developer React/.NET ",
    desc: "ILM education center",
  },
];

export default Data;
